### ISSUE TITLE
webdriver is causing error with jasmine

### ISSUE THREAD

**Issue by npvn** [xolvio/meteor-webdriver#6]
https://gist.github.com/anonymous/4838773d3b94363752a7

Steps to reproduce the error (Meteor 1.0.2.1):

_ `meteor create testApp`

_ Add the following packages to testApp:
```
sanjo:jasmine
velocity:html-reporter
xolvio:webdriver
```

_ Run the app. In velocity overlay, click on buttons to add sample jasmine tests.

_ Restart meteor. You'll see the error.

_ If you remove `xolvio:webdriver` the error is gone

**Comment by samhatoum** [comment]
thanks for the detailed report, I'll look into it soon

**Comment by samhatoum** [comment]
This is fixed in the latest version

**Comment by annachu** [comment]
Hmm...I am still getting the same error when I follow the steps listed above. In my case, I tried adding Jasmine integration client tests through the velocity overlay.

I am using the latest versions of the following packages:
* sanjo:jasmine (0.9.3)
* velocity:html-reporter (0.3.2)
* xolvio:webdriver (0.1.6)

By the way, I'm really enjoying your Meteor Testing book!

Thanks!

**Comment by samhatoum** [comment]
fixed in xolvio:webdriver@0.1.7

**Comment by annachu** [comment]
Great! Thanks so much :)

**Comment by samhatoum** [comment]
no problem, and I'm glad you're enjoying the book!
